name: contrail_ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.16.4
  - scipy>=1.2.1
  - scikit-learn>=0.24.1
  - matplotlib
  - seaborn
  - pandas
  - absl-py
  - pytorch
  - jupyterlab
  - google-cloud-storage
  - rich
  - pre-commit
  - black
  - ruff
  - pip
