name: radio_ml
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy>=1.16.4
  - scipy>=1.2.1
  - scikit-learn>=0.24.1
  - matplotlib
  - seaborn
  - pandas
  - astropy
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - jupyterlab_code_formatter
  - optuna
  - optuna-dashboard
  - rich
  - Pillow
  - h5py
  - pyside6
  - pre-commit
  - black
  - ruff
  - nbqa
  - pip
  - pip:
    - jupyterlab-optuna
