[paths]
data = "./data/"
model = "./build/models/"

[mode]
verbose = true
gpu = true

[meta]
batch_size = 256
epochs = 300
loss_func = "mse"

[model]
name = "ResNet"

[net_hyperparams]
num_classes = 4
hidden_channels = [16, 32, 64, 128]
block_groups = [2, 2, 2, 2]
block_name = "ResBlock"
activation_name = "relu"

[optimizer]
name = "SGD"

[optimizer_hyperparams]
lr = 0.1
momentum = 0.9
weight_decay = 1e-4
