"galaxy_data.zip" = "https://zenodo.org/record/7689127/files/galaxy_data.zip?download=1"
"galaxy_data_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_h5.zip?download=1"
"galaxy_data_crossvalid_0_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_0_h5.zip?download=1"
"galaxy_data_crossvalid_1_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_1_h5.zip?download=1"
"galaxy_data_crossvalid_2_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_2_h5.zip?download=1"
"galaxy_data_crossvalid_3_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_3_h5.zip?download=1"
"galaxy_data_crossvalid_4_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_4_h5.zip?download=1"
"galaxy_data_crossvalid_test_h5.zip" = "https://zenodo.org/record/7689127/files/galaxy_data_crossvalid_test_h5.zip?download=1"
