[paths]
data = "../data/galaxy_data/all"
model = "../build/checkpoints/"

[mode]
verbose = true
gpu = true

[meta]
save_name = "ResNet18_2048"
batch_size = 30
epochs = 180
loss_func = "mse"

[model]
name = "ResNet"

[net_hyperparams]
num_classes = 4
hidden_channels = [16, 32, 64, 128, 256, 512, 1024, 2048]
block_groups = [2, 2, 2, 2, 2, 2, 2, 2]
block_name = "ResBlock"
activation_name = "relu"

[optimizer]
name = "SGD"

[optimizer_hyperparams]
lr = 0.4
momentum = 0.5
weight_decay = 1e-3
