[paths]
data = "./data/"
model = "./build/models/"

[mode]
verbose = true
gpu = true

[meta]
save_name = "ResNet18"
batch_size = 20
epochs = 180
loss_func = "mse"

[model]
name = "ResNet"

[net_hyperparams]
num_classes = 4
hidden_channels = [16, 32, 64, 128]
block_groups = [4, 4, 4, 4]
block_name = "ResBlock"
activation_name = "mish"

[optimizer]
name = "SGD"

[optimizer_hyperparams]
lr = 0.1
momentum = 0.9
weight_decay = 1e-4
