[paths]
data = "../data/galaxy_data/all"
model = "../build/checkpoints/"

[mode]
verbose = true
gpu = true

[meta]
save_name = "resnet_tuning_ROC_AUC_noBN_drop"
batch_size = 200
epochs = 90
loss_func = "mse"

[model]
name = "ResNet"

[net_hyperparams]
num_classes = 4
hidden_channels = [16, 32, 64, 128]
block_groups = [4, 4, 4, 4]
block_name = "PreActBlock"
activation_name = "mish"

[optimizer]
name = "SGD"

[optimizer_hyperparams]
lr = 0.1
momentum = 0.9
weight_decay = 1e-4


[tuning]
hidden_channels = [4, 8, 16, 32]
num_groups = [1, 4, 1]
block_groups = [1, 4, 1]
block_names = ["ResBlock", "PreActBlock"]
activation_names = ["relu", "prelu", "mish"]
optimizers = ["SGD", "Adam"]
lr = [1e-9, 0.4]
momentum = [0.1, 1.0, 0.1]
weight_decay = [1e-8, 1e-1]
dropout = [0.0, 0.9, 0.1]
